import pandas as pd
import json

with open("./data/similar_for_sale_demo_data.json") as f:
    data_for_sale = json.load(f)

# Use pd.json_normalize to convert the JSON to a DataFrame
df_for_sale = pd.json_normalize(data_for_sale['results'], 
                     meta=[["address", "city"],
["address", "state"],
["address", "streetAddress"],
["address", "zipcode"],
["attributionInfo", "agentName"],
["attributionInfo", "agentPhoneNumber"],
["attributionInfo", "brokerName"],
["attributionInfo", "brokerPhoneNumber"],
["attributionInfo", "mlsId"],
["attributionInfo", "mlsName"],
["attributionInfo", "providerLogo"],
["attributionInfo", "trueStatus"],
"bathrooms",
"bedrooms",
"currency",
"hdpUrl",
"homeStatus",
"homeType",
"isPremierBuilder",
"isZillowOwned",
"latitude",
["listing_sub_type", "is_FSBA"],
["listing_sub_type", "is_FSBO"],
["listing_sub_type", "is_bankOwned"],
["listing_sub_type", "is_comingSoon"],
["listing_sub_type", "is_forAuction"],
["listing_sub_type", "is_foreclosure"],
["listing_sub_type", "is_newHome"],
"livingArea",
"livingAreaUnits",
"livingAreaUnitsShort",
"livingAreaValue",
"longitude",
"lotAreaUnits",
"lotAreaValue",
"lotSize",
["miniCardPhotos", "url"],
"newConstructionType",
"price",
"providerListingID",
"state",
"zpid"])

with open("./data/similar_sold_demo_data.json") as f:
    data_sold = json.load(f)

# Use pd.json_normalize to convert the JSON to a DataFrame
df_sold = pd.json_normalize(data_sold['results'],
                     meta=[["address", "city"],
                           ["address", "state"],
["address", "streetAddress"],
["address", "zipcode"],
["attributionInfo", "agentName"],
["attributionInfo", "agentPhoneNumber"],
["attributionInfo", "brokerName"],
["attributionInfo", "brokerPhoneNumber"],
["attributionInfo", "mlsId"],
["attributionInfo", "mlsName"],
["attributionInfo", "providerLogo"],
"bathrooms",
"bedrooms",
"currency",
"dateSold",
"daysOnZillow",
"hdpUrl",
"homeStatus",
"homeType",
"isPremierBuilder",
"isZillowOwned",
"latitude",
["listing_sub_type", "is_FSBA"],
["listing_sub_type", "is_FSBO"],
["listing_sub_type", "is_bankOwned"],
["listing_sub_type", "is_comingSoon"],
["listing_sub_type", "is_forAuction"],
["listing_sub_type", "is_foreclosure"],
["listing_sub_type", "is_newHome"],
"livingArea",
"livingAreaUnits",
"livingAreaUnitsShort",
"livingAreaValue",
"longitude",
"lotAreaUnits",
"lotAreaValue",
"lotSize",
"newConstructionType",
"price",
"providerListingID",
"state",
"zpid"])

#print(df_for_sale)
#print(df_sold)